apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # namespace: dev # Specify the target namespace
spec:
  replicas: 1 # Number of NGINX pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Use the desired NGINX image
        ports:
        - containerPort: 80