apiVersion: v1
kind: Service
metadata:
  name: dev
  namespace: my-nginx-namespace # Specify the target namespace
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Or NodePort, LoadBalancer depending on your needs